### ISSUE TITLE
컨트롤러 메소드 return 타입에 관한 의견 입니다.

### ISSUE THREAD

**Issue by yeoncheol-jang** [codej99/SpringRestApi#22]
안녕하세요. 개발자님 코드를 보면서 열심히 공부 중인 학생입니다.

1. 의견: 컨트롤러 메소드들의 return 타입이 CommonResult, SingleResult, ListResult 입니다. 현재는 HTTP response status line에 200 혹은 500 상태 코드만 나오는 상황인데요. RESTful API에 맞게 status line의 상태코드도 직접 지정해주면 어떨까 생각합니다.

2. 해결책 제시: 
ex) 생성의 경우 CREATED를 이용하여 201 코드를 내려주면 더 명확하지 않을까 생각합니다. 다른 것들도 마찬가지구요. 
ResponseEntity<CommonResult>
return new ResponseEntity<>(responseService.getCustomException(), HttpStatus.CREATED);

만약에 이 방법이 괜찮다면 return 타입을 ResponseEntity로 변경 후 pull request 하겠습니다. 

아직 공부하는 학생입장이라 부족하지만, 가볍게 읽어주시면 감사하겠습니다!

**Comment by codej99** [comment]
안녕하세요. 
의견 감사합니다~
네 말씀하신 의견이 REST API의 요건에 맞습니다~!
당연히 생성과 관련된 HttpStatus Code는 201 CREATED가 내려가는게 더 명시적으로 좋습니다.
그런데 이건 개인적인 의견이구요.
현업에선 서버와 프론트 개발자가 갈라져 있는 경우엔 의견이 다른 경우가 발생하여 의견을 맞춰야 하는 경우도 발생했습니다.
그냥 api 성공이면 200으로 다 통일해서 처리하자, 아니다 그건 표준에 위배되니 각 상황에 맞게 200, 201과 같이 구분해서 처리하자.
그리고 성공인 경우(2xx)에 추가 결과를 줘야하는 경우도 있습니다.
그래서 api를 보시면 아시겠지만 httpstatus code와 별개로 body에 추가로 success, code, msg를 보내는 것을 볼 수 있습니다.
왜 중복되게 결과를 두개 보내냐 그럴 수 있겠지만 httpstatus code는 정해진 값이기 때문에 이와 별개로 좀더 상세한 정보를 주거나 하기 위해서는 추가 정보가 필요해서
그렇게 처리합니다.
 
아무튼 좋은 의견 감사합니다.~!
 
 
-----Original Message-----
From: "YEONCHEOL ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-05-23 (일) 18:06:44 (GMT+09:00)
Subject: [codej99/SpringRestApi] 컨트롤러 메소드 return 타입에 관한 의견 입니다. (#22)
 
안녕하세요. 개발자님 코드를 보면서 열심히 공부 중인 학생입니다.

의견: 컨트롤러 메소드들의 return 타입이 CommonResult, SingleResult, ListResult 입니다. 현재는 HTTP response status line에 200 혹은 500 상태 코드만 나오는 상황인데요. RESTful API에 맞게 status line의 상태코드도 직접 지정해주면 어떨까 생각합니다.

해결책 제시:
ex) 생성의 경우 CREATED를 이용하여 201 코드를 내려주면 더 명확하지 않을까 생각합니다. 다른 것들도 마찬가지구요.
ResponseEntity
return new ResponseEntity<>(responseService.getCustomException(), HttpStatus.CREATED);


아직 공부하는 학생입장이라, 가볍게 읽어주시면 감사하겠습니다!

**Comment by yeoncheol-jang** [comment]
아~하긴 그냥 HTTP status code는 200으로 통일 한 후에 body에 따로 실어서 보내면 되긴 하겠네요...오히려 업무에서는 더 편리할것 같다는 생각도 듭니다..
알려주셔서 감사합니다!
